[build]
  publish = "carmenAndDave/public"
  command = "cd carmenAndDave && hugo --gc"

[build.environment]
  HUGO_VERSION = "0.83.1"
  HUGO_THEME = "airspace-hugo"
  HUGO_BASEURL = "/"

# Spanish subpages 404
[[redirects]]
  from = "/es/*"
  to = "/es/404.html"
  status = 404

# Romanian subpages 404
[[redirects]]
  from = "/ro/*"
  to = "/ro/404.html"
  status = 404

# all other pages 404 (incl. those in `defaultContentLanguage`)
# NOTE that in case you've set `defaultContentLanguageInSubdir = true` in `config.toml`, you need to change the destination below to point to the `defaultContentLanguage` subdir, e.g. `to = "/en/404.html"`
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
